### PR TITLE
Change helper scripts to use less permissions

### PR DESCRIPTION
**Pull request by p-rintz**
Hey,

these are the changes Id propose for issue #5 .

One thing first though, Im not sure if you meant to include config/users.json and repo.json or not.
They were added to git, but also excluded in the .gitignore. I removed the files, so they are now properly excluded.
This might be an issue if you do not create empty/default files on first startup though.

For the other changes:

- I changed the permissions of the backup files to $user:borgwarehouse + chmod 750, so that borgwarehouse does not need root permissions for some things it does.

As for the sudoers file, it could look like the following. 
Sadly, regex are only available starting with sudo version 1.9.10 and Ubuntu 20.04 as well as Debian Stable do not have this version. 
Which is why I had to work with the old capabilities.
Regex would make this better still.

I found the following [site](https://facelessuser.github.io/wcmatch/fnmatch/) pretty helpful for documentation.

```
borgwarehouse ALL=(ALL) NOPASSWD: /usr/sbin/userdel -rf [[\:xdigit\:]]*
borgwarehouse ALL=(ALL) NOPASSWD: /usr/sbin/useradd -d /var/borgwarehouse/[[\:xdigit\:]]* -s /bin/bash -m [[\:xdigit\:]]*
borgwarehouse ALL=(ALL) NOPASSWD: /usr/bin/mkdir -p /var/borgwarehouse/[[\:xdigit\:]]*/repos/repo[[\:digit\:]]*, /usr/bin/mkdir -p /var/borgwarehouse/[[\:xdigit\:]]*/.ssh
borgwarehouse ALL=(ALL) NOPASSWD: /usr/bin/touch /var/borgwarehouse/[[\:xdigit\:]]*/.ssh/authorized_keys
borgwarehouse ALL=(ALL) NOPASSWD: /usr/bin/chmod -R 750 /var/borgwarehouse/[[\:xdigit\:]]*, /usr/bin/chmod 600 /var/borgwarehouse/[[\:xdigit\:]]*/.ssh/authorized_keys
borgwarehouse ALL=(ALL) NOPASSWD: /usr/bin/chown -R [[\:xdigit\:]]*\:borgwarehouse /var/borgwarehouse/[[\:xdigit\:]]*
borgwarehouse ALL=(ALL) NOPASSWD: /usr/bin/tee /var/borgwarehouse/[[\:xdigit\:]]*/.ssh/authorized_keys
borgwarehouse ALL=(ALL) NOPASSWD: /usr/bin/sed -ri s|*|g /var/borgwarehouse/[[\:xdigit\:]]*/.ssh/authorized_keys

```

### CODE REVIEW

**Comment by Ravinou** [comment]
Hey, thanks for your work, I'll check.

For your first question : 
`config/repo.json` contains an empty array needed for initialization. This file should be left by default for users who do freshinstall.

`config/users.json` is the users file contains the default user admin and a default password admin. It's the same, you have to leave this file as it is for freshinstall.

 I look at and test the rest of your commits.

**Comment by p-rintz** [comment]
Ive re-added the json files then and removed them from the gitignore.

**Comment by Ravinou** [comment]
> * I changed the permissions of the backup files to $user:borgwarehouse + chmod 750, so that borgwarehouse does not need root permissions for some things it does.

You make me curious ! Why is it important to put the rights on the group (750) instead of just on the user borgwarehouse (700) as I did before? What do you gain by doing this? Thanks :)

What is the point of changing line 84 of 
`sudo chown -R ${user}:${user} ${home}`
into :
`sudo chown -R ${user}:borgwarehouse ${home}`
knowing that the user variable is already equal to "borgwarehouse" ?

I ask you this question because I intend (one day) to pass some parameters in environment variable, especially the repo directory (actually /var/borgwarehouse) because some people asking me to do it.

**Comment by p-rintz** [comment]
> You make me curious ! Why is it important to put the rights on the group (750) instead of just on the user borgwarehouse (700) as I did before?

But it's currently not `borgwarehouse`.
The ${user} is the randomly generated repository user. 

So it looks like this:
```
# ls -lah /var/borgwarehouse/
drwxr-x---  4 029c1c1b borgwarehouse 4.0K Dec 12 12:50 029c1c1b
```

You generate the name in line https://github.com/Ravinou/borgwarehouse/blob/38824c2c6b148c1c8a0beaeac6e62c8a551438e6/helpers/shells/createRepo.sh#L43

**Comment by Ravinou** [comment]
of course... I hadn't had my coffee yet when I woke up 🤪😁

**Review by Ravinou — APPROVED** [review]
Great job, thank you Philipp 🎉

**Pull request merged**
