### PR TITLE
WIP: nss_wrapper

### PR DESCRIPTION
**Pull request by dhenry123**
- Adding nss_wrapper support to switch user in the entrypoint
- sshd configuration 
- rsyslog.conf configuration
- bash profile configuration (nss_wrapper suport)
- supervisord.conf
- entrypoint to prepare environment

### CODE REVIEW

**Comment by dhenry123** [comment]
Explanation : 
The container starts with the uid provided in the Dockerfile or the uid provided by the process (docker rootless -u uid:group, kubernetes,...). 
In simple cases, you can start your container with another uid, but in other cases, such as sshd, the latter requires your uid to be mapped to a user in the /etc/passwd file. nss_wrapper takes care of this operation.

**Comment by dhenry123** [comment]
You can try this version, but I got several "zombie" sshd processes. The analysis is in progress...

**Comment by dhenry123** [comment]
```mermaid
graph TD
stdout(container STDOUT)
s(Sshd)
bh(Borgwarehouse)
rsyslogd
s-->|stdout & stderr|sshdlogfile-->rsyslogd
bh-->|stdout & stderr|bglogfile-->rsyslogd
rsyslogd-->stdout

```

**Comment by dhenry123** [comment]
```mermaid
graph LR
tmp(tmp files Volume /tmp - temporary volume needed if read-only startup)
cf(config files Volume /home/borgwarehouse/app/config)
repos(config files Volume /home/borgwarehouse/app/repos)
ks(sshd key files Volume /etc/ssh)
as(sshd authorized_keys Volume /home/borgwarehouse/.ssh)
s(Sshd)

sd(Supervisord)
bh(Borgwarehouse)
sd-->|read & write|tmp
s-->|read & write|ks
s-->|read & write|as
s-->|write pid|tmp
s-->|write log|tmp
bh-->|read & write|cf
bh-->|write|repos
bh-->|write log|tmp
```

**Comment by dhenry123** [comment]
Tested on kubernetes Read only, uid; 1253662 gid: 4564521

**Comment by dhenry123** [comment]
sources : 
- https://www.man7.org/linux/man-pages/man8/rsyslogd.8.html
- http://supervisord.org/index.html
- https://rsyslog.readthedocs.io/en/latest/configuration/modules/imfile.html
- https://linux.die.net/man/8/sshd

**Review by Ravinou — APPROVED** [review]

**Comment by Ravinou** [comment]
A huge, BIG HUGE thank you ❤️
I'll test it !

**Pull request merged**
